const SubstitutionList =[
    {name:"allspice", equivalence:"1 teaspoon of this is equivalent to", options: [ "1/2 teaspoon cinnamon", "1/4 teaspoon ginger", "1/4 teaspoon cloves"]},
    {name:"arrowroot starch", equivalence:"1 teaspoon of this is equivalent to", options:["1 tablespoon flour", "1 teaspoon cornstarch"]},
    {name:"baking mix", equivalence:"1 cup of this is equivalent to", options:["1 cup pancake mix"]},
    {name:"baking powder", equivalence:"1 teaspoon of this is equivalent to", options:["1/4 teaspoon baking soda plus 1/2 teaspoon cream of tartar","1/4 teaspoon baking soda plus 1/2 cup buttermilk (decrease liquid in recipe by 1/2 cup)"]},
    {name:"baking soda", equivalence:"1 teaspoon of this is equivalent to", options:["4 teaspoons baking powder","1 teaspoon potassium bicarbonate and 1/3 teaspoon salt. NOTE: If the recipe calls for an acidic liquid such as sour cream, yogurt, buttermilk, vinegar, molasses, or citrus juice, you should replace it with the same amount of whole milk"]},
    {name:"beer", equivalence:"1 cup of this is equivalent to", options:["1 cup nonalcoholic beer", "1 cup chicken broth"]},
    {name:"brandy", equivalence:"1/4 cup of this is equivalent to", options:["1 teaspoon imitation brandy extract plus enough water to make 1/4 cup"]},
    {name:"bread crumbs", equivalence:"1 cup of this is equivalent to", options:["1 cup cracker crumbs", "1 cup matzo meal", "1 cup ground oats"]},
    {name:"brown sugar", equivalence:"1 cup, packed of this is equivalent to", options:["1 cup white sugar plus 1/4 cup molasses and decrease the liquid in recipe by 1/4 cup", "1 cup white sugar", "1 1/4 cups confectioners' sugar"]},
    {name:"butter", equivalence:"1 cup of this is equivalent to", options:["1 cup shortening", "7/8 cup vegetable oil", "7/8 cup lard"]},
    {name:"buttermilk", equivalence:"1 cup of this is equivalent to", options:["1 cup yogurt", "1 tablespoon lemon juice or vinegar plus enough milk to make 1 cup"]},
    {name:"white sugar", equivalence:"1 cup of this is equivalent to", options:["1 cup brown sugar", "1 1/4 cups confectioners' sugar", "3/4 cup honey", "3/4 cup corn syrup"]},
    {name:"cheddar cheese", equivalence:"1 cup shredded of this is equivalent to:", options:[ "1 cup shredded Colby cheddar", "1 cup shredded Monterey Jack cheese"]},
    {name:"cocoa", equivalence:"1/4 cup of this is equivalent to:", options:["1 (1-ounce) square unsweetened chocolate"]},
    {name:"corn syrup", equivalence:"1 cup of this is equivalent to:", options:["1 1/4 cup white sugar plus 1/3 cup water", "1 cup honey", "1 cup light treacle syrup"]},
    {name:"cottage cheese", equivalence:"1 cup of this is equivalent to:", options:["1 cup farmer's cheese", "1 cup ricotta cheese"]},
    {name:"heavy cream", equivalence:"1 cup of this is equivalent to:", options:["1 cup evaporated milk", "3/4 cup milk plus 1/3 cup butter"]},
    {name:"light cream", equivalence:"1 cup of this is equivalent to", options:["1 cup evaporated milk", "3/4 cup milk plus 3 tablespoons butter"]},
    {name:"whipped cream", equivalence: "1 cup of this is equivalent to", options:["1 cup frozen whipped topping, thawed"]},
    {name:"eggs", equivalence: "1 whole egg (3 tablespoons or 1.7 oz) is equivalent to", options:["2 1/2 tablespoons of powdered egg substitute plus 2 1/2 tablespoons water", "1/4 cup liquid egg substitute", "1/4 cup silken tofu pureed", "3 tablespoons mayonnaise", "half a banana mashed with 1/2 teaspoon baking powder", "1 tablespoon powdered flax seed soaked in 3 tablespoons water"]},
    {name:"evaporated milk", equivalence: "1 cup of this is equivalent to", options:["1 cup light cream"]},
    {name:"bread flour", equivalence:"1 cup is equivalent to", options:["1 cup all-purpose flour plus 1 teaspoon wheat gluten"]},
    {name:"garlic", equivalence:"1 clove of this is equivalent to", options:["1/8 teaspoon garlic powder", "1/2 teaspoon granulated garlic", "1/2 teaspoon garlic salt, reduce salt in recipe"]},
    {name:"gelatin", equivalence:"1 tablespoon of this is equivalent to", options:["2 teaspoons agar agar"]},
    {name:"green onion", equivalence:"1/2 cup of this is equivalent to", options:[ "1/2 cup chopped onion", "1/2 cup chopped leek", "1/2 cup chopped shallots"]},
    {name:"hazelnuts", equivalence:"1 cup of this is equivalent t", options:["1 cup macadamia nuts", "1 cup almonds"]},
    {name:"herbs", equivalence:"1 tablespoon chopped fresh herbs is equivalent to", options:["1 teaspoon (chopped or whole leaf) dried herbs"]},
    {name:"herring", equivalence:"8 ounces of this is equivalent to"  , options:["8 ounces of sardines"]},
    {name:"honey", equivalence: "1 cup of this is equivalent to" , options:[ "1 1/4 cup white sugar plus 1/3 cup water", "1 cup corn syrup", "1 cup light treacle syrup"]},
    {name:"hot pepper sauce", equivalence:"1 teaspoon of this is equivalent to", options:["3/4 teaspoon cayenne pepper plus 1 teaspoon vinegar"]},
    {name:"lard", equivalence: "1 cup of this is equivalent to" , options:["1 cup shortening", "7/8 cup vegetable oil", "1 cup butter"]},
    {name:"lemon grass", equivalence: "2 fresh stalks of this is equivalent to" , options:["1 tablespoon lemon zest"]},
    {name:"milk", equivalence:"1 cup of this is equivalent to", options:["1 cup soy milk", "1 cup rice milk", "1 cup water or juice", "1/4 cup dry milk powder plus 1 cup water", "2/3 cup evaporated milk plus 1/3 cup water"]},
    {name:"mustard", equivalence:"1 tablespoon of this is equivalent to", options:["Mix 3/4 cup brown sugar and 1 teaspoon cream of tartar"]},
    {name:"orange juice", equivalence:"1 tablespoon of this is equivalent to", options:["1 tablespoon other citrus juice"]},
    {name:"sour cream", equivalence:"1 cup of this is equivalent to", options:[ "1 tablespoon vinegar or lemon juice mixed with enough milk to make 1 cup: Let stand 5 minutes to thicken"]},
    {name:"key lime juice", equivalence:"1 teaspoon of this is equivalent to", options:["1 teaspoon vinegar", "1 teaspoon white wine", "1 teaspoon lemon juice"]},
    {name:"lime zest", equivalence:"1 teaspoon of this is equivalent to", options:["1 teaspoon lemon zest"]},
    {name:"sweetened condensed milk", equivalence:"1 (14-ounce) can of this is equivalent to", options:["3/4 cup white sugar mixed with 1/2 cup water and 1 1/8 cups dry powdered milk: Bring to a boil and cook, stirring frequently, until thickened, about 20 minutes"]},
    //    {name:"", equivalence:"", options:[]},
    //
    // "lemon juice": ["1 teaspoon of this is equivalent to", "1/2 teaspoon vinegar", "1 teaspoon white wine", "1 teaspoon lime juice"],
    // "lemon zest": ["1 teaspoon of this is equivalent to", "1/2 teaspoon lemon extract", "2 tablespoons lemon juice"],
    // "macadamia nuts": ["1 cup of this is equivalent to", "1 cup almonds", "1 cup hazelnuts"],
    // "mace": ["1 teaspoon of this is equivalent to", "1 teaspoon nutmeg"],
    // "margarine": ["1 cup of this is equivalent to", "1 cup shortening plus 1/2 teaspoon salt", "1 cup butter", "7/8 cup vegetable oil plus 1/2 teaspoon salt", "7/8 cup lard plus 1/2 teaspoon salt"],
    // "mayonnaise": ["1 cup of this is equivalent to", "1 cup sour cream", "1 cup plain yogurt"],
    // "mint": ["1/4 cup of this is equivalent to", "1 tablespoon dried mint leaves"],
    // "molasses": ["1 cup of this is equivalent to", "Mix 3/4 cup brown sugar and 1 teaspoon cream of tartar"],
    // "onion": ["1 cup (chopped) of this is equivalent to", "1 cup chopped green onions", "1 cup chopped shallots", "1 cup chopped leeks", "1/4 cup dried minced onion", "1/4 cup onion powder"],
    // "orange zest": ["1 tablespoon of this is equivalent to", "1/2 teaspoon orange extract", "1 teaspoon lemon juice"],
    // "parmesan cheese": ["1/2 cup (grated) of this is equivalent to", "1/2 cup grated Asiago cheese", "1/2 cup grated Romano cheese"],
    // "parsley": ["1 tablespoon of this is equivalent to", "1 tablespoon chopped fresh chervil", "1 teaspoon dried parsley"],
    // "pepperoni": ["1 ounce of this is equivalent to", "1 ounce salami"],
    // "raisin": ["1 cup of this is equivalent to", "1 cup dried currants", "1 cup dried cranberries", "1 cup chopped pitted prunes"],
    // "rice": ["1 cup (cooked) of this is equivalent to", "1 cup cooked barley", "1 cup cooked bulgur", "1 cup cooked brown or wild rice"],
    // "ricotta": ["1 cup of this is equivalent to", "1 cup dry cottage cheese", "1 cup silken tofu"],
    // "rum": ["1 tablespoon of this is equivalent to", "1/2 teaspoon rum extract, plus enough water to make 1 tablespoon"],
    // "saffron": ["1/4 teaspoon of this is equivalent to", "1/4 teaspoon turmeric"],
    // "salami": ["1 ounce of this is equivalent to", "1 ounce pepperoni"],
    // "chocolate chips": ["1 cup of this is equivalent to", "1 cup chocolate candies", "1 cup peanut butter or other flavored chips", "1 cup chopped nuts", "1 cup chopped dried fruit"],
    // "shallots": ["1/2 cup of this is equivalent to", "1/2 cup chopped onion", "1/2 cup chopped leek", "1/2 cup chopped green onion"],
    // "shortening": ["1 cup of this is equivalent to", "1 cup butter", "1 cup margarine minus 1/2 teaspoon salt from recipe"],
    // "sour milk": ["1 cup of this is equivalent to", "1 tablespoon vinegar or lemon juice mixed with enough milk to make 1 cup: Let stand 5 minutes to thicken"],
    // "soy sauce": ["1/2 cup of this is equivalent to", "1/4 cup Worcestershire sauce mixed with 1 tablespoon water"],
    // "stock": ["1 cup of this is equivalent to", "1 cube beef or chicken bouillon dissolved in 1 cup water"],
    // "vegetable oil": ["1 cup of this is equivalent to", "1 cup applesauce", "1 cup fruit puree"],
    // "vinegar": ["1 teaspoon of this is equivalent to", "1 teaspoon lemon or lime juice", "2 teaspoons white wine"],
    // "wine": ["1 cup of this is equivalent to", "1 cup chicken or beef broth", "1 cup fruit juice mixed with 2 teaspoons vinegar", "1 cup water"],
    // "yeast": ["1 (.25-ounce) package of this is equivalent to", "1 cake compressed yeast", "2 1/2 teaspoons active dry yeast", "2 1/2 teaspoons rapid rise yeast"],
    // "yogurt": ["1 cup of this is equivalent to", "1 cup sour cream", "1 cup buttermilk", "1 cup sour milk"]
] ;
export default  SubstitutionList;
